### ISSUE TITLE
Change CI solution

### ISSUE THREAD

**Issue by wleoncio** [ltronneb/bayesynergy#4]
TravisCI has been shut off for open-source projects back in June, which is why https://travis-ci.org/ocbe-uio/bayesynergy is stuck on a commit from 4 months ago. I suggest moving the CI workflow for bayessynergy to a different system. I've been using GitHub Actions for this, and I can take care of the migration if you want.

**Comment by ltronneb** [comment]
Would be wonderful if you could do that @wleoncio!
